apiVersion: v1
data:
  FLYWAY_PASSWORD: password
  FLYWAY_URL: jdbc:postgresql://dab-p3-database-9255dce1-9359-48e4-9f9d-37ad7eba2a33:5432/database
  FLYWAY_USER: username
  PGDATABASE: database
  PGHOST: dab-p3-database-9255dce1-9359-48e4-9f9d-37ad7eba2a33
  PGPASSWORD: password
  PGPORT: "5432"
  PGUSER: username
  POSTGRES_DB: database
  POSTGRES_PASSWORD: password
  POSTGRES_USER: username
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: flyway-project-env
  name: project-env
