version: "3.4"

services:
  bitly:
    build: bitly
    image: bitly
    restart: "no"
    volumes:
      - ./bitly/:/app
    ports:
      - 3000:3000
    depends_on:
      - database
      - flyway
    env_file:
      - project.env

  database:
    container_name: dab-p1-database-9255dce1-9359-48e4-9f9d-37ad7eba2a33
    image: postgres:14.1
    restart: "no"
    env_file:
        - project.env

  flyway:
    image: flyway/flyway:8.4.0-alpine
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
